---
title: Wrecktangle
timezone: UTC
collections:
  config:
    title: Config
    output: true
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
<<<<<<< HEAD
  - scope:
      path: projects
      type: projects
    values:
      project-image:
      project-description:
      colors:
  - scope:
      path: ""
      type: posts
    values:
      - main-image:
        sub-title:
        length:
        is-extenal:
        external-url:
=======
- scope:
    path: projects
    type: projects
  values:
    project-image: 
    project-description: 
    colors: 
    layout: project
- scope:
    path: ''
    type: posts
  values:
    Content:
    - main-image: 
      sub-title: 
      length: 
      is-extenal: 
      external-url: 
>>>>>>> ea18a4928722e1ba3345c01b34fc398fda868972
email: your-email@example.com
phone: 01234 567 890
address: 51 Bracken Road, Sandyford, Dublin, D18&nbsp;CV48
instagram: Instagram
twitter: Twitter
facebook: Facebook
description: Solutions outside the box
url: https://harryfischer.github.io/wrecktangle/
twitter_username: 
github_username: HarryFischer
copyright: Wrecktangle
theme: minima
sass:
  style: compressed
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-seo-tag
