---
title: Wrecktangle
timezone: UTC
collections:
  config:
    title: Config
    output: true
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
phone: 01234 567 890
address: 28 Blackberry Hill, Carrickmines, Dublin 18. D18 H869
instagram: Instagram
twitter: Twitter
facebook: Facebook
description: Solutions outside the box
url: https://harryfischer.github.io/wrecktangle/
twitter_username:
github_username: HarryFischer
copyright: Wrecktangle
theme: minima
sass:
  style: compressed
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
      type: "project"
    values:
      - project-image:
        project-description:
        project-colour:
