---
title: Wrecktangle
timezone: UTC
collections:
  config:
    title: Config
    output: true
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    main-image: 
    image-caption: 
    alt: 
    sub-title: 
    length: 
    is-extenal: 
    external-url: 
- scope:
    path: ''
    type: projects
  values:
    project-image: 
    project-description: 
    color-name: 
    content-block:
    - layout: 
      image: 
      image-caption: 
      alt: 
      array:
      - question: 
        answer-text: 
      video-url: 
      left-color-name: 
      right-color-name: 
      has-grey-background: 
    layout: project
email: info@wrecktangle.ie
phone: "+353 (0)1 539 2793"
address: 51 Bracken Road, Sandyford, Dublin, D18&nbsp;CV48
description: Solutions outside the box. Wrecktangle is a strategic commercial consultancy,
  specialising in the Leisure and Tourism industry. We collaborate with you, so your
  big ideas can turn into the bigger picture.
url: https://wrecktangle.ie
github_username: HarryFischer
copyright: Wrecktangle
theme: minima
sass:
  style: compressed
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-redirect-from
